Many corrections of the PowerPoint quiz
Ebazhanov/linkedin-quiz-assessments pull request #955
Opened 2021-01-08 19:51 UTC by schoppfe

- Replacement of " = " by checkboxes " - [x] "
- Adaptation of various punctuation marks according to grammar
- Some correction of upper and lower case letters
- Q2: It's NOT the "Layout tools". In MS PP 2019 it's called "Drawing Tools". There is no such answer but in there is a function called "Arrange"
- Q5: Sould be in the printer window not in the options menu
- Q6: What!? The best tab for adding objects is of course Insert and not Files
- Q8: Grammar (https://support.microsoft.com/en-us/office/rules-for-the-accessibility-checker-651e08f2-0fc3-4e10-aaca-74b4a67101c1?ns=powerpnt&version=16&ui=en-us&rs=en-us&ad=us)
- Q9: No, atleast not in MSPP2019. There you have to use Table Tools -> Design Tab -> Table Styles
- Q12: No no no, Slide Show Tab -> Set Up Slide Show -> Show options -> Loop continuously until 'Esc'
- Q14: "Highlight the content you want to use as a slide title, and select Heading 1 in Styles. Highlight the content you want to use as the slide text, and select Heading 2 in Styles." If your Word document contains no Heading 1 or Heading 2 styles, PowerPoint will create a slide for each paragraph in your content.
- Q15: Corrected from "by date" to "by author
- Q16: No it's automatic. If hidden is selected the courser stays hidden no matter what!
- Q19: Selected an answer
- Q21: Selected an answer
- Added Q22, Q23, Q24, Q25, Q26, Q27, Q28, Q29, Q30, Q31, Q32, Q33

2021-01-09 09:20 UTC, Ebazhanov requested changes
Hello, Felix @schoppfe! Thank you for the detailed PR message and I think it would be great if you will move some of your explanations inside the *.md file because after merge they will disappear. I will add some examples please follow them for the rest of your changes. Thank you in advance!

2021-01-09 09:20 UTC, Ebazhanov commented on microsoft-power-point/microsoft-power-point-quiz.md
> +- [x] Arrange tools
```suggestion
- [x] Arrange tools // It's NOT the "Layout tools". In MS PP 2019 it's called "Drawing Tools". There is no such answer but there is a function called "Arrange"

```

2021-01-09 09:20 UTC, Ebazhanov commented on microsoft-power-point/microsoft-power-point-quiz.md
> +- [x] the Print dialog box
```suggestion
- [x] the Print dialog box // Should be in the printer window not in the options menu
```

2021-01-09 14:58 UTC, Ebazhanov commented on microsoft-power-point/microsoft-power-point-quiz.md
> +```Personal Hint: There are multiple file suffixes for templates (.potx, .potm, .pot).```
good point 👍

2021-01-09 14:58 UTC, Ebazhanov commented on microsoft-power-point/microsoft-power-point-quiz.md
> +```
like

2021-01-14 01:13 UTC, schoppfe commented on microsoft-power-point/microsoft-power-point-quiz.md
> +- [x] grammar
- [x] grammar // [Source](https://support.microsoft.com/en-us/office/rules-for-the-accessibility-checker-651e08f2-0fc3-4e10-aaca-74b4a67101c1?ns=powerpnt&version=16&ui=en-us&rs=en-us&ad=us)

2021-01-14 06:57 UTC, Ebazhanov requested changes
ah, mist! @schoppfe can you please fix conflicts between your branch and master? Thank you in advance! 
![image](https://user-images.githubusercontent.com/13170022/104555435-298d0180-563e-11eb-9392-e63cd66f4c59.png)

2021-01-14 08:46 UTC, Ebazhanov approved these changes
Super, cool! Danke @schoppfe! :punch:
Und einen schönen :sunny: Tag noch

2021-01-14 08:47 UTC, merged